### ISSUE TITLE
Auto-Channel vs. Smart-Channel

### ISSUE THREAD

**Issue by pingywon** [G4lile0/ESP32-WiFi-Hash-Monster#14]
Can someone explain to me the difference between the two? I guess I understand that Auto-Channel will channel hop in channel order, but what is it that Smart-Channel is doing?

**Comment by G4lile0** [comment]
**Auto-Channel** hop in channel order defined on the variable:
`int autoChannels[] = {1, 6, 11};   `
after the defined here:
`#define AUTO_CHANNEL_INTERVAL 15000 // how often to switch channels automatically, in milliseconds`

**Smart-Channel**  is bit more tricky, as it cover all the channels sequentially, but only hop if there is not new SSID, EAPOL or DEAUTHS after the time defined on the _AUTO_CHANNEL_INTERVAL_

**Comment by pingywon** [comment]
Thank you!
