### ISSUE TITLE
arduino compile error

### ISSUE THREAD

**Issue by LuckyFishGeek** [G4lile0/ESP32-WiFi-Hash-Monster#43]
environment and equipment

ESP32 version 1.0.4

M5stack-fire
![Snipaste_2022-08-26_16-36-56](https://user-images.githubusercontent.com/29472751/186860572-a585cc8f-7ccd-44af-b904-15e71f071d1f.png)

**Comment by Bartix765** [comment]
Try changing it to random(0,13). The arduino library random function does not have a option with no arguments.
