### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by cookins** [G4lile0/ESP32-WiFi-Hash-Monster#9]
Hello.
I'm sorry about question, it's not exactly about firmware, at least partly. So on this firmware, what average power consumption on m5stack core unit? Or at least tell me for how long will it run? They selling with additional battery, so I'm curious what will be difference. Thanks and sorry once more.

**Comment by G4lile0** [comment]
Using the "incognito mode" will disable the display and the led bars to reduce the consumption, so it will run for a few hours, if you plan to run for long periods I suggest you to use an external power bank.

**Comment by RChadwick7** [comment]
I measured about 100mA with the display off, and about 120mA with it on.

**Comment by cookins** [comment]
> I measured about 100mA with the display off, and about 120mA with it on.

Really? Even esp8266's consumption was 215 mAh, while transmitting data at full power. It's cool, thanks.
